{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "tests\\ui\\test_login_page.py:16: in test_login_negative\n    login_page.login_negative('milanakan2001@gmail.com','12345')\npages\\login_page.py:42: in login_negative\n    self.navigate_to()\npages\\base_page.py:16: in navigate_to\n    self.page.goto(full_url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE   playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE   Call log:\nE     - navigating to \"https://app.clickup.com/login\", waiting until \"load\""}, "description": "Проверка успешной авторизации и наличия элемента 'Board' после входа.", "steps": [{"name": "Открытие страницы входа и попытка авторизации с некорректными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\tests\\ui\\test_login_page.py\", line 16, in test_login_negative\n    login_page.login_negative('milanakan2001@gmail.com','12345')\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 16, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Неудачная авторизация с логином: 'milanakan2001@gmail.com' и неверным паролем: '12345'", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 16, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход на страницу входа", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\pages\\login_page.py\", line 42, in login_negative\n    self.navigate_to()\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 16, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход по URL страницы", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\clickup\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\clickup\\pages\\base_page.py\", line 16, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\clickup\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1744745670438, "stop": 1744745701495}], "start": 1744745670438, "stop": 1744745701497}], "parameters": [{"name": "username", "value": "'milanakan2001@gmail.com'"}, {"name": "password_invalid", "value": "'12345'"}], "start": 1744745670438, "stop": 1744745701498}], "start": 1744745669984, "stop": 1744745701504}], "start": 1744745669984, "stop": 1744745701507, "uuid": "3bce3047-2683-4ae7-9eb5-e2fc671553b8", "historyId": "21f5678c3abeecd832fe4240961d2fdf", "testCaseId": "21f5678c3abeecd832fe4240961d2fdf", "fullName": "tests.ui.test_login_page#test_login_negative", "labels": [{"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "DESKTOP-G6JEM9V"}, {"name": "thread", "value": "17420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}